
name: build

on:
  
  push:
    branches: 
      - CRITICAL'
    tags:
      - 'v[0-9].[0-9]'
  pull_request:
    branches: [ "CRITICAL" ]

jobs:
  build:
    #if: ${{ !startwith(commit,#NORUN)}}
    runs-on: ubuntu-latest
    steps:
      # 2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'first.table'
          severity: 'CRITICAL'   
      

      # 4
      
    
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mozlau/cicd:${{github.sha}}
      
      - 
        name: install cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.2.0'
      
      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}"
        env:
          TAGS: 'mozlau/cicd'
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      # 
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: 'good' # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Name: LIUBAO\nMatriculation: A0286053A\nEmail:<e1221865@u.nus.edu>\n<https://github.com/MozLau/LAUBAO_CICDWORKSHOP.git>\nDocker:'
          SLACK_TITLE: Information
          SLACK_USERNAME: CICD
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK_TEST }}

      - name: upload
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{secrets.WEBHOOK_TEST_TOKEN}}
          channel_id: ${{secrets.WEBHOOK_TEST_ID}}
          content: 'file content'
          file_type: 'text'
          file_name: 'trivy-result.txt'
          title: 'title of file'
          initial_comment: 'post by LAUBAO' 
          
        

     
