
name: first

on:
  
  push:
    branches: 
      - 'test'
    tags:
    - 'v*'
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name : echo
        run : echo ${{github.ref}}
